### ISSUE TITLE
Suggest from elftune

### ISSUE THREAD

**Issue by YuzuRyo61** [YuzuRyo61/KotohiraYu#7]
誤字修正の提案。

新規詐欺は行けませんっ！！
↓
新規詐欺はいけませんっ！！

**Comment by elftune** [comment]
よろしくお願いいたします(笑)

**Comment by YuzuRyo61** [comment]
修正させていただきました〜、提案ありがとうございますっ👍

**Comment by elftune** [comment]
あれ？　13:36に試してみましたが、変わってなかったような…
まだ早かったでしょうか？(汗)

**Comment by YuzuRyo61** [comment]
> あれ？　13:36に試してみましたが、変わってなかったような…
> まだ早かったでしょうか？(汗)

ユウちゃんはうちのメインサーバーで動かしているので、うちが適用するまで反映されないのです( ˘ω˘)

ちょっと早かったようです。
