### ISSUE TITLE
1投稿に複数の起動キーワードが含まれる際に連続して投稿してしまう

### ISSUE THREAD

**Issue by rosylilly** [YuzuRyo61/KotohiraYu#8]
## 内容
1投稿に複数の起動キーワードが含まれる際に連続して投稿してしまう

## いつ頃に起きた？
常に

## 補足
普段は別に構わないのですが、高負荷時に負荷上昇の DoS 手段として悪用されうる可能性があり、懸念しています

**Comment by YuzuRyo61** [comment]
改善させていただきましたっ、提案ありがとうございましたっ
